=== Francesdbz18/LMARCDAM/Fevoli_Francesco-LDM_EV02_PRACT_EV/XSD/catalogo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="catalogoLibro" type="catalogoLibroType"/>

  <xs:complexType name="fechaType">
    <xs:sequence>
      <xs:element type="xs:string" name="mes" minOccurs="0"/>
      <xs:element name="anyo">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="libroType">
    <xs:sequence>
      <xs:element name="titulo">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
      <xs:element name="autor" maxOccurs="unbounded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
      <xs:element type="fechaType" name="fecha"/>
      <xs:element name="ISBN">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
      <xs:element name="editor">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="categoria" use="optional"/>
    <xs:attribute type="xs:string" name="enstock" use="optional"/>
    <xs:attribute type="xs:string" name="revisor" use="optional"/>
  </xs:complexType>

  <xs:complexType name="catalogoLibroType">
    <xs:sequence>
      <xs:element type="libroType" name="libro" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== Francesdbz18/LMARCDAM/Fevoli_Francesco-LDM_EV02_PRACT_EV/XSD/catalogo.xml
<catalogoLibro xsi:noNamespaceSchemaLocation="catalogo.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <libro categoria="ficcion" enstock="true" revisor="">
        <titulo>Las hijas de la criada</titulo>
        <autor>Sonsoles Ónega</autor>
        <fecha>
            <anyo>2008</anyo>
        </fecha>
        <ISBN>978-8408280170</ISBN>
        <editor>Planeta</editor>
    </libro>
    <libro categoria="noficcion" enstock="false" revisor="Luis Rodriguez">
        <titulo>Lenguajes de marcas y sistemas de gestión de información</titulo>
        <autor>J.M. Castro Ramos</autor>
        <autor>J. R. Rodríguez Sánchez</autor>
        <fecha>
            <mes>Septiembre</mes>
            <anyo>2012</anyo>
        </fecha>
        <ISBN>978-84-1545-217-1</ISBN>
        <editor>Garceta</editor>
    </libro>
</catalogoLibro>
