=== Francesdbz18/LMARCDAM/Fevoli_Francesco-LDM_EV02_PRACT_EV/XSD/personas2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="tipoDia">
    <xs:restriction base="xs:positiveInteger">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="31"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoMes">
    <xs:restriction base="xs:positiveInteger">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="12"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoAnyo">
    <xs:restriction base="xs:positiveInteger">
      <xs:minInclusive value="1900"/>
      <xs:maxInclusive value="2011"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoNombre">
    <xs:restriction base="xs:string">
      <xs:maxLength value="50"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoCodPostal">
    <xs:restriction base="xs:integer">
      <xs:totalDigits value="5"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="personas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="persona" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="persona">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="tipoNombre"/>
        <xs:element name="apellidos" type="tipoNombre"/>
        <xs:element name="telefono" type="xs:string" minOccurs="0"/>
        <xs:element name="nacimiento" minOccurs="0">
          <xs:complexType>
            <xs:attribute name="dia" type="tipoDia" default="1"/>
            <xs:attribute name="mes" type="tipoMes" default="1"/>
            <xs:attribute name="anyo" type="tipoAnyo" default="1900"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="direccion" type="direccion" minOccurs="1" maxOccurs="unbounded"/>
        <xs:choice>
          <xs:element name="varon" minOccurs="0"/>
          <xs:element name="hembra" minOccurs="0"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="direccion">
    <xs:sequence>
      <xs:element name="calle" type="tipoNombre"/>
      <xs:element name="ciudad" type="tipoNombre"/>
      <xs:element name="codigo_postal" type="tipoCodPostal"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== Francesdbz18/LMARCDAM/Fevoli_Francesco-LDM_EV02_PRACT_EV/XSD/personas2.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xsi:noNamespaceSchemaLocation="personas2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <persona>
        <nombre>Juan</nombre>
        <apellidos>Pardo</apellidos>
        <nacimiento dia="10" mes="4" anyo="1982"></nacimiento>
        <direccion>
            <calle>Caoba, 1</calle>
            <ciudad>Madrid</ciudad>
            <codigo_postal>28005</codigo_postal>
        </direccion>
        <varon/>
    </persona>
    <persona>
        <nombre>María</nombre>
        <apellidos>López</apellidos>
        <direccion>
            <calle>Roncato, 1, Illescas</calle>
            <ciudad>Toledo</ciudad>
            <codigo_postal>45200</codigo_postal>
        </direccion>
        <direccion>
            <calle>Paseo de la Esperanza 15, 1º A</calle>
            <ciudad>Madrid</ciudad>
            <codigo_postal>28005</codigo_postal>
        </direccion>
    </persona>
</personas>
